### ISSUE TITLE
Error while importing on Win10

### ISSUE THREAD

**Issue by AlphaNumeric99** [banderlog/opencv-python-inference-engine#7]
I did

```
pip3 uninstall opencv-python
pip3 uninstall opencv-contrib-python
pip3 install opencv-python-inference-engine
```

Now i get the error 

`ModuleNotFoundError: No module named 'cv2.cv2'
`
When i do:
`    import cv2
`

**Comment by varunjain3** [comment]
I had the same error

**Comment by banderlog** [comment]
Well, I've just checked it within virtualenv and conda with python 3.6 on Ubuntu 20.04 LTS and everything works.

@AlphaNumeric99 I was able to replicate results using wrong pip. 
Can you add the output of `which -a pip` to your question please? It looks like you are using python from conda and pip from the system. 

For virtualenv:
```bash
virtualenv --clear --always-copy -p /usr/bin/python3.6 ./venv
./venv/bin/pip install opencv-python-inference-engine
./venv/bin/python
# in python
import cv2
```

For conda:
```bash
# install conda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash ./Miniconda3-latest-Linux-x86_64.sh
# apply license
# default path is OK
# Do you wish the installer to initialize Miniconda3? -- NO

# create env
source ~/miniconda3/etc/profile.d/conda.sh
conda create -n test_env python=3.6
conda activate test_env

# you need to use a right pip
which -a pip
>>/home/user/miniconda3/envs/test_env/bin/pip
>>/home/user/.local/bin/pip
>>/home/user/.local/bin/pip
>>/home/user/.local/bin/pip
>>/home/user/.local/bin/pip

# install
/home/user/miniconda3/envs/test_env/bin/pip install opencv-python-inference-engine
# it must be listed in output
/home/user/miniconda3/envs/test_env/bin/pip list

python3
# in python
import cv2
```

**Comment by banderlog** [comment]
@varunjain3 are you using linux subsystem (WSL)? If so, you probably have the same problem. If not -- [use it](https://www.pcworld.com/article/3106463/how-to-get-bash-on-windows-10-with-the-anniversary-update.html), it is good (no GPU, though).

I've checked it on win10 LTSC with Ubuntu 18.04 WSL -- all is ok.

**Comment by AlphaNumeric99** [comment]
@banderlog  Sorry i forgot to mention i am also running windows 10

Here's the code you asked me to run. I think its 'where' in windows instead of 'which'

Also i did change pip3->pip in the code i mentioned in the question

```
(base) C:\Users\xyz>activate tf15

(tf15) C:\Users\xyz>which pip
'which' is not recognized as an internal or external command,
operable program or batch file.

(tf15) C:\Users\xyz>where pip
D:\Anaconda3\envs\tf15\Scripts\pip.exe
D:\Anaconda3\Scripts\pip.exe

(tf15) C:\Users\xyz>python -V
Python 3.7.1

(tf15) C:\Users\xyz>pip -V
pip 19.3.1 from D:\Anaconda3\envs\tf15\lib\site-packages\pip (python 3.7)

```

**Comment by banderlog** [comment]
@AlphaNumeric99 I see. I never tested it with conda that was installed system-wide on windows. I'll try it on VM but it will take some time.

**Comment by AlphaNumeric99** [comment]
Thank you!
and for cuda support maybe you can make a pip/conda package of https://jamesbowley.co.uk/accelerate-opencv-4-3-0-build-with-cuda-and-python-bindings/ because i couldn't figure out for the life of me how to install this pre built binary and i sure many people like me who are beginners have the same issue.

**Comment by banderlog** [comment]
**To the original issue**

I am an idiot, the answer to your question is pretty obvious -- you get this error because there is no windows compatible libraries compiled in the package. As it stated in README:
> I had not made builds for Windows or MacOS.

Probably I need to modify the wheel naming, so you will not be able to install it on windows and get to this error.
I do not want to mess with windows and crosscompilation and other things, thus you will not see such package from me.
Use WSL, as I stated above, or another package.

**On the CUDA**
I will not build a separate package with CUDA support, it is meaningless. There few versions of CUDA and CUDNn libraries with different combinations for different GPUs and there is no way to compile OpenCV in a way when it will support them all. And you will need to download CUDA/CUDNn libraries from nvidia manually -- no "an ability to fast deploy a small package" here.
Also, I wanted this package for CPU inference only.
Here is an excellent guide how to compile OpenCV with CUDA: https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/
